### PR TITLE
Extend docs

### PR DESCRIPTION
**Pull request by rgieseke**
Pinging @znicholls 
What else should we add here, more details on development/contributing probably?
As discussed in #129 and #116.

### CODE REVIEW

**Comment by znicholls** [comment]
I think that's basically all of it. Once we have those you could then pick it up, look at the examples, read through contributing and developing and add something, completing the full pipeline?

**Comment by rgieseke** [comment]
I've added a "Developing" section, not sure we need more than the "Contributing" currently in Readme, what do you think?

**Comment by znicholls** [comment]
> not sure we need more than the "Contributing" currently in Readme, what do you think?

Also not sure we need it right now. I think the aim will be something like what we have in magicc or in scmcallib but doesn't need to be immediate

**Comment by rgieseke** [comment]
Alright ... if you're happy with the current state, we can merge.

**Comment by rgieseke** [comment]
Would be good if we (=you) do the next release together and add anything that's missing/not working well.

**Pull request merged**
