### PR TITLE
Make test-pypi-install also test imports of all dependencies

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added (N/A)
- [x] Documentation added (N/A)
- [x] Example added (N/A)
- [x] Description in ``CHANGELOG.rst`` added (N/A)

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <http://link-to-pr.com>`_) Added feature which does something
- (`#XX <http://link-to-pr.com>`_) Fixed bug identified in (`#XX <http://link-to-issue.com>`_)
```

Just makes sure that when we import pymagicc, we go through and import all the dependencies in submodules too to double check that all the dependencies are importable (i.e. installed correctly)

### CODE REVIEW

**Comment by rgieseke** [comment]
So this ensures that every (sub-)module can be imported without error? Shouldn't this be checked locally?

**Comment by rgieseke** [comment]
It does work locally of course, just trying to better understand the use-case. Maybe it should also print something like "All submodules imported successfully", or just print "import pymagicc.io" and so on.

In any case it's good to have the check of the PyPI version in a separate file. One could also think about printing the PyPI version for comparison (but that's probably a separate issue).
It's available from their JSON API:
https://pypi.org/pypi/pymagicc/json

**Comment by znicholls** [comment]
When I was developing netcdfscm, at first after a pip install the top level
import would work and I only realised that not all dependencies were
installing properly once I tried to import a submodule. This tweak just
made sure I would be alerted if the same issue were to arise again.

Happy to tweak printing and do pypi checks as you see fit

**Comment by rgieseke** [comment]
I'm wondering if this should be part of the test suite ...

And also if after a `pip install` more or all tests should be run -- it's easy to miss some data files in MANIFEST or `setup.py` and then things don't actually work ...

**Comment by znicholls** [comment]
With CI we could do a nightly pip install to check. Everytime doesn't work
I don't think cause you have to pip release before you know if it's a good
idea or not..

Running tests would force users to install all the test requirements, could
be undesirable..

**Comment by rgieseke** [comment]
Alrighty! We can re-consider later (or create separate issues) ...

**Pull request merged**
