### PR TITLE
Doc generation automation

### PR DESCRIPTION
**Pull request by znicholls**
A good enough for now start on #114 

Raises #117

### CODE REVIEW

**Comment by znicholls** [comment]
> Does docs/sitemap.xml.gz need to be there?

I have no idea, I just adding everything that wasn't being ignored by `.gitignore`...

Happy to adjust as you want

**Comment by znicholls** [comment]
have pushed what I get, still have the `gz` file but have added to `.gitignore`, happy to merge when u r

**Comment by rgieseke** [comment]
Alright, I seem to have an older Mkdocs version.

**Comment by rgieseke** [comment]
Ok, so using the newer version I don't get any differences any more.
It's probably fine to ignore the .gz file and i prefer not to have too many binary files in the repo :-)

**Pull request merged**
