### PR TITLE
Diagnose TCR and ECS

### PR DESCRIPTION
**Pull request by znicholls**
The input api is still a bit nasty but this functionality is useful so I figure we can bring this in and I can fix the api in #49

### CODE REVIEW

**Comment by rgieseke** [comment]
This looks super nice! I'd maybe replace "Your TCR ECS results" with "The TCR ECS results" (as in "not your fault" ...

Maybe it's also easier to always return the full result set and not have the added complexity of `full_results`.

**Comment by znicholls** [comment]
Where is 'Your TCR ECS results'? 

> Maybe it's also easier to always return the full result set and not have the added complexity of full_results.

I thought about that but I figured that mucking around working out which year is the 70th year of increase etc. was simple functionality I could provide so just did it...

**Comment by rgieseke** [comment]
> Where is 'Your TCR ECS results'?

In the potentially very useful error messages, should have written [results], sorry.

> I thought about that but I figured that mucking around working out which year is the 70th year of increase etc. was simple functionality I could provide so just did it...

Maybe we can have both, useful summary and full results by default?

**Comment by znicholls** [comment]
Looks good now

**Pull request merged**
