### PR TITLE
Docs fixups

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
- (#XX)[http://link-to-pr.com] Fixed bug identified in (issue)[http://link-to-issue.com]
```

### CODE REVIEW

**Comment by rgieseke** [comment]
Looks good to me, only one question about the path fiddling:

@swillner Why was the path fiddling necessary? https://github.com/openclimatedata/pymagicc/pull/146/commits/6f42943ad82e32d1bd122452aa8b285141d857dd

If the path is not set Sphinx explicitly will use whatever Pymagicc version is installed, right?

**Comment by znicholls** [comment]
I think the default Sphinx config file is out of date. Maybe that path fiddling was a good idea in the past but no longer I think. 

> If the path is not set Sphinx explicitly will use whatever Pymagicc version is installed, right?

Yep/whatever it finds when it imports pymagicc, which is the behaviour we want I think (given devs should be working in a virtual env)

**Comment by rgieseke** [comment]
> Yep/whatever it finds when it imports pymagicc, which is the behaviour we want I think (given devs should be working in a virtual env)

Good point, and the version should be stated clearly in the template.

What happens on ReadTheDocs?

**Comment by znicholls** [comment]
> What happens on ReadTheDocs? (Edit: Which version wil it use?)

Good question. pip installable latest?

**Comment by znicholls** [comment]
Turns out it explodes (https://readthedocs.org/projects/netcdf-scm/builds/7940589/), undoing that change then

**Comment by rgieseke** [comment]
Alright I'm merging this then ...

**Comment by rgieseke** [comment]
@znicholls There are settings on Readthedocs (I've added you as a maintainer) for requirements files etc. -- but I think having this set in `conf.py` is probably easier to find (than a setting on RTD).

**Pull request merged**
