### PR TITLE
Add rebase to pull request steps

### PR DESCRIPTION
**Pull request by znicholls**
Attempt to keep things a bit cleaner

Please confirm that this pull request has done the following:

- [ ] Rebased

### CODE REVIEW

**Comment by rgieseke** [comment]
Couldn't we just enforce this via the repo settings?

**Comment by znicholls** [comment]
> Couldn't we just enforce this via the repo settings?

If that's possible, sounds good!

**Comment by rgieseke** [comment]
Set "merge commits" to not allowed, do we still need this then?

**Comment by znicholls** [comment]
Nope!

**Pull request closed without merging**
